desc "Builds project"
lane :buildProject do
  scan(derived_data_path: "dd", build_for_testing: true)
end

desc "Runs tests"
lane :doTests do
  scan(derived_data_path: "dd", test_without_building: true)
end

desc "Does all the stuff needed for CI"
lane :doCIStuff do
  buildProject
  doTests
end