name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - name: Build
      run: bundle exec fastlane doCIStuff
    - name: Invoke deployment hook
    - uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.WEBHOOK_URL }}
        title: "Build"
        description: "Building and testing successful"
        color: 0x0000ff
        username: GitHub
